package fr.cnrs.lacito.fieldarchive.dtos;

import java.util.ArrayList;
import java.util.List;

public class NlQueryRequest {
    public String requestId;   // generated by the dialog, used to cancel
    public String provider;    // claude | openai | local | builtin
    public String question;
    public List<NlClarification> clarifications = new ArrayList<>();
}
